// src/constants/destinations.js - Expanded Database with Indian & International Places
const destinationsDatabase = [
  // International Destinations
  {
    id: 'paris',
    title: 'Paris, France',
    subtitle: 'Romantic streets, art museums & exquisite cuisine',
    category: 'International',
    duration: '5-7 days',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=800&h=500&fit=crop',
    highlight: 'Eiffel Tower, Louvre Museum, Seine River cruises',
    budget: 'moderate',
    interests: 'Art, History, Fine Dining',
    season: 'Apr-Oct'
  },
  {
    id: 'tokyo',
    title: 'Tokyo, Japan',
    subtitle: 'Urban energy, neon lights & sushi paradise',
    category: 'International',
    duration: '4-6 days',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&h=500&fit=crop',
    highlight: 'Shibuya Crossing, Senso-ji Temple, Tsukiji Fish Market',
    budget: 'moderate',
    interests: 'Technology, Food, Culture',
    season: 'Mar-May, Sep-Nov'
  },
  {
    id: 'switzerland',
    title: 'Switzerland',
    subtitle: 'Alpine peaks, scenic trains & chocolate paradise',
    category: 'International',
    duration: '7-10 days',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?w=800&h=500&fit=crop',
    highlight: 'Jungfraujoch, Matterhorn, Lake Geneva',
    budget: 'luxury',
    interests: 'Mountains, Adventure, Scenic Beauty',
    season: 'Jun-Sep, Dec-Mar'
  },
  {
    id: 'london',
    title: 'London, UK',
    subtitle: 'Royal history, modern culture & pub vibes',
    category: 'International',
    duration: '5-7 days',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=800&h=500&fit=crop',
    highlight: 'Buckingham Palace, London Eye, British Museum',
    budget: 'moderate',
    interests: 'History, Museums, Theatre',
    season: 'May-Sep'
  },
  {
    id: 'bali',
    title: 'Bali, Indonesia',
    subtitle: 'Tropical beaches, rice terraces & spiritual retreats',
    category: 'International',
    duration: '6-8 days',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=800&h=500&fit=crop',
    highlight: 'Ubud Monkey Forest, Tanah Lot Temple, Seminyak Beach',
    budget: 'budget',
    interests: 'Beaches, Temples, Yoga, Nature',
    season: 'Apr-Oct'
  },
  {
    id: 'dubai',
    title: 'Dubai, UAE',
    subtitle: 'Luxury shopping, desert safaris & modern marvels',
    category: 'International',
    duration: '4-5 days',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=500&fit=crop',
    highlight: 'Burj Khalifa, Palm Jumeirah, Desert Safari',
    budget: 'luxury',
    interests: 'Shopping, Architecture, Adventure',
    season: 'Nov-Mar'
  },

  // Indian Destinations
  {
    id: 'goa',
    title: 'Goa, India',
    subtitle: 'Sunny beaches, Portuguese heritage & vibrant nightlife',
    category: 'Indian',
    duration: '4-6 days',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1512343879784-960f3d9f6e8a?w=800&h=500&fit=crop',
    highlight: 'Baga Beach, Dudhsagar Falls, Old Goa Churches',
    budget: 'budget',
    interests: 'Beaches, Nightlife, Water Sports',
    season: 'Nov-Feb'
  },
  {
    id: 'jaipur',
    title: 'Jaipur, India',
    subtitle: 'Pink City, royal palaces & vibrant bazaars',
    category: 'Indian',
    duration: '3-4 days',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?w=800&h=500&fit=crop',
    highlight: 'Hawa Mahal, Amer Fort, City Palace',
    budget: 'budget',
    interests: 'History, Architecture, Shopping',
    season: 'Oct-Mar'
  },
  {
    id: 'kerala',
    title: 'Kerala, India',
    subtitle: 'Backwaters, lush greenery & Ayurvedic retreats',
    category: 'Indian',
    duration: '5-7 days',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&h=500&fit=crop',
    highlight: 'Alleppey Backwaters, Munnar Tea Gardens, Kovalam Beach',
    budget: 'moderate',
    interests: 'Nature, Wellness, Houseboats',
    season: 'Sep-Mar'
  },
  {
    id: 'ladakh',
    title: 'Ladakh, India',
    subtitle: 'High-altitude desert, Buddhist monasteries & adventure',
    category: 'Indian',
    duration: '6-8 days',
    rating: 4.9,
    image: 'https://images.unsplash.com/photo-1589182373726-e4f658ab1acf?w=800&h=500&fit=crop',
    highlight: 'Pangong Lake, Nubra Valley, Khardung La Pass',
    budget: 'moderate',
    interests: 'Adventure, Photography, Buddhism',
    season: 'Jun-Sep'
  },
  {
    id: 'manali',
    title: 'Manali, India',
    subtitle: 'Snow-capped peaks, river rafting & adventure sports',
    category: 'Indian',
    duration: '4-5 days',
    rating: 4.5,
    image: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=800&h=500&fit=crop',
    highlight: 'Rohtang Pass, Solang Valley, Hadimba Temple',
    budget: 'budget',
    interests: 'Adventure, Snow, Trekking',
    season: 'Dec-Feb, May-Jun'
  },
  {
    id: 'varanasi',
    title: 'Varanasi, India',
    subtitle: 'Spiritual capital, Ganga Aarti & ancient temples',
    category: 'Indian',
    duration: '2-3 days',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1561361058-c24cecae35ca?w=800&h=500&fit=crop',
    highlight: 'Ganga Aarti, Kashi Vishwanath Temple, Sarnath',
    budget: 'budget',
    interests: 'Spiritual, Culture, History',
    season: 'Oct-Mar'
  },
  {
    id: 'udaipur',
    title: 'Udaipur, India',
    subtitle: 'City of Lakes, majestic palaces & romantic sunsets',
    category: 'Indian',
    duration: '3-4 days',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1565183928294-7063f23ce0f8?w=800&h=500&fit=crop',
    highlight: 'Lake Pichola, City Palace, Jag Mandir',
    budget: 'moderate',
    interests: 'Romance, History, Photography',
    season: 'Sep-Mar'
  },
  {
    id: 'mysore',
    title: 'Mysore, India',
    subtitle: 'Royal heritage, illuminated palace & sandalwood',
    category: 'Indian',
    duration: '2-3 days',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1593591614089-2a7d8c4c31d4?w=800&h=500&fit=crop',
    highlight: 'Mysore Palace, Chamundi Hills, Brindavan Gardens',
    budget: 'budget',
    interests: 'History, Architecture, Culture',
    season: 'Oct-Mar'
  },

  // More International
  {
    id: 'bangkok',
    title: 'Bangkok, Thailand',
    subtitle: 'Street food, temples & vibrant nightlife',
    category: 'International',
    duration: '4-6 days',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=800&h=500&fit=crop',
    highlight: 'Grand Palace, Wat Arun, Chatuchak Market',
    budget: 'budget',
    interests: 'Food, Temples, Nightlife',
    season: 'Nov-Feb'
  },
  {
    id: 'singapore',
    title: 'Singapore',
    subtitle: 'Garden city, futuristic architecture & shopping paradise',
    category: 'International',
    duration: '4-5 days',
    rating: 4.7,
    image: 'https://images.unsplash.com/photo-1525625293386-3f2f0b4c5f9f?w=800&h=500&fit=crop',
    highlight: 'Marina Bay Sands, Gardens by the Bay, Sentosa',
    budget: 'luxury',
    interests: 'Shopping, Family, Architecture',
    season: 'Feb-Apr, Nov-Dec'
  },
  {
    id: 'dubai',
    title: 'Dubai, UAE',
    subtitle: 'Luxury shopping, desert safaris & modern marvels',
    category: 'International',
    duration: '4-5 days',
    rating: 4.6,
    image: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=500&fit=crop',
    highlight: 'Burj Khalifa, Palm Jumeirah, Desert Safari',
    budget: 'luxury',
    interests: 'Shopping, Architecture, Adventure',
    season: 'Nov-Mar'
  },
  {
    id: 'barcelona',
    title: 'Barcelona, Spain',
    subtitle: 'Gaudí architecture, beaches & tapas',
    category: 'International',
    duration: '4-6 days',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?w=800&h=500&fit=crop',
    highlight: 'Sagrada Familia, Park Güell, Las Ramblas',
    budget: 'moderate',
    interests: 'Architecture, Food, Beach',
    season: 'May-Oct'
  },
  {
    id: 'newyork',
    title: 'New York, USA',
    subtitle: 'The city that never sleeps, Broadway & landmarks',
    category: 'International',
    duration: '5-7 days',
    rating: 4.8,
    image: 'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=800&h=500&fit=crop',
    highlight: 'Times Square, Central Park, Statue of Liberty',
    budget: 'luxury',
    interests: 'Shopping, Theater, Landmarks',
    season: 'Apr-Jun, Sep-Nov'
  }
]

export default destinationsDatabase